inherit_from: .rubocop_todo.yml
require:
  - rubocop-performance
  - rubocop-rails
  # - rubocop-rspec

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Gemspec/OrderedDependencies:
  Exclude:
    - 'hituzi.gemspec'

Metrics/LineLength:
  Max: 120

# ---

Metrics/AbcSize:
  Max: 47

Metrics/BlockLength:
  Max: 29

Metrics/ClassLength:
  Max: 206

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 37

Metrics/ModuleLength:
  Max: 117

Metrics/PerceivedComplexity:
  Max: 10
